# Generated by Django 4.2.8 on 2024-01-01 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0002_alter_user_is_active"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="auth_provider",
            field=models.CharField(
                choices=[("email", "email"), ("google", "google")],
                default="email",
                max_length=10,
                verbose_name="Auth Provider",
            ),
        ),
    ]
